spring.application.name=MembershipOnboarding
spring.datasource.driver-class-name=org.apache.derby.iapi.jdbc.AutoloadedDriver
spring.datasource.url=jdbc:derby:membershipDB;create=true
spring.jpa.database-platform=org.hibernate.community.dialect.DerbyDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
#security
spring.security.user.name=admin
spring.security.user.password=root
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp